### ISSUE TITLE
invalid json format

### ISSUE THREAD

**Issue by higherkuo** [Azure-Samples/iot-hub-c-intel-edison-client-app#5]
The `int readMessage(int messageId, char *payload)` function does not write the valid json format to `payload`. Hence, the backend javascript example ([visualizing in webapp](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-live-data-visualization-in-web-apps)) cannot parse the bytes correctly. Adding quotes fixes the problem.

**Comment by yuwzho** [comment]
@higherkuo Thanks for your reporting, now the code is fixed with pullrequest #6 . You can check the newest code. 😄
